### ISSUE TITLE
CPANPLUS-Dist-Fedora: test suite fails on non-Fedora/CentOS systems

### ISSUE THREAD

**Issue by eserte** [shlomif/cpanplus-dist-backends#1]
The test suite fails on debian, ubuntu, freebsd ... like this:
```
[ERROR] Not on a Fedora system


#   Failed test 'CPANPLUS::Dist::Fedora Format is available'
#   at t/unit.t line 27.
[ERROR] Not on a Fedora system

[ERROR] Format 'CPANPLUS::Dist::Fedora' is not available


#   Failed test 'Dist created with target => init'
#   at t/unit.t line 45.
Can't call method "status" on an undefined value at t/unit.t line 48.
# Looks like your test exited with 2 just after 5.
t/unit.t ........ 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 8/11 subtests 
```

While the distribution name makes it clear that the module is not expected to run on these systems, it would be good to have some kind of "controlled" failure, e.g. refusing to build the distribution at all (which would cause "NA" reports on CPAN Testers, not FAILs), or skip the tests on non-Fedora/CentOS systems.

**Comment by shlomif** [comment]
Thanks for the report, @eserte ! I've suspected this would happen on non-Fedora systems and will try to fix it soon.

**Comment by shlomif** [comment]
In v0.4.2 (which I uploaded now) I skip the tests if `$TEST_CPANPLUS_FEDORA` is not true (because they may fail n fedora/etc. too if some tools/libraries are absent). Feel free to close this ticket if the tests pass globally. Thanks!

**Comment by shlomif** [comment]
closing for now.
